<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="input\**" />
    <Compile Remove="output\**" />
    <EmbeddedResource Remove="input\**" />
    <EmbeddedResource Remove="output\**" />
    <None Remove="input\**" />
    <None Remove="output\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Manager.txt" />
    <None Remove="ManagerListing.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.*" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\CommonHTTP\CommonHttp.csproj" />
	  <ProjectReference Include="..\Common\CommonTcp.csproj" />
	</ItemGroup>

</Project>
